/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;
import javax.swing.JOptionPane;

public class NewJFrame extends javax.swing.JFrame {

    int N=0;
    String A;
    String B;
    String C;
    String D;
    String E;
    String F;
    String G;
    String H;
    String I;
    public NewJFrame() {
        initComponents();
        int N=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton1 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        Boton7 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        Separador = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ta Te Ti", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N
        jPanel1.setFont(new java.awt.Font("MS PGothic", 0, 11)); // NOI18N

        Boton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Boton1.setToolTipText("");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        Boton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Boton2.setToolTipText("");
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });

        Boton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Boton3.setToolTipText("");
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });

        Boton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Boton4.setToolTipText("");
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });

        Boton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Boton5.setToolTipText("");
        Boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton5MouseClicked(evt);
            }
        });
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });

        Boton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Boton6.setToolTipText("");
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });

        Boton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Boton7.setToolTipText("");
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });

        Boton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Boton8.setToolTipText("");
        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });

        Boton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Boton9.setToolTipText("");
        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });

        Separador.setBackground(new java.awt.Color(255, 102, 204));
        Separador.setForeground(new java.awt.Color(153, 255, 102));
        Separador.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Resetear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Separador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Los vacia
        Boton1.setText("");
        Boton2.setText("");
        Boton3.setText("");
        Boton4.setText("");
        Boton5.setText("");
        Boton6.setText("");
        Boton7.setText("");
        Boton8.setText("");
        Boton9.setText("");
        // Los tira enabled
        Boton1.setEnabled(true);
        Boton2.setEnabled(true);
        Boton3.setEnabled(true);
        Boton4.setEnabled(true);
        Boton5.setEnabled(true);
        Boton6.setEnabled(true);
        Boton7.setEnabled(true);
        Boton8.setEnabled(true);
        Boton9.setEnabled(true);
        // Reinicia el turno al jugador que pone X
        N = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Boton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MouseClicked

    }//GEN-LAST:event_Boton5MouseClicked

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
       if (N==0){
            Boton1.setText("X");
            N = 1;
            } else {
                 Boton1.setText("O");
                 N = 0;
                    }
            Boton1.setEnabled(false);
            //----------------------- 
            A = Boton1.getText();
            B = Boton2.getText();
            C = Boton3.getText();
            D = Boton4.getText();
            E = Boton5.getText();
            F = Boton6.getText();
            G = Boton7.getText();
            H = Boton8.getText();
            I = Boton9.getText();
            //-----------------------
if ("X".equals(A)){
if (((A.equals(E))&&(E.equals(I)))||((A.equals(D))&&(D.equals(G)))||((A.equals(B))&&(B.equals(C)))){
        JOptionPane.showMessageDialog(null, "Gano el jugador con X","Ganador",JOptionPane.INFORMATION_MESSAGE);
        Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
            } else{}
}
if ("O".equals(A)){
    if (((A.equals(E))&&(E.equals(I)))||((A.equals(D))&&(D.equals(G)))||((A.equals(B))&&(B.equals(C)))){
        JOptionPane.showMessageDialog(null, "Gano el jugador con O","Ganador",JOptionPane.INFORMATION_MESSAGE);
        Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
    } else {}
}
    

    
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
            if (N==0){
            Boton5.setText("X");
            N = 1;
            } else {
                 Boton5.setText("O");
                 N = 0;
                    }
            Boton5.setEnabled(false);
            //----------------------- 
            A = Boton1.getText();
            B = Boton2.getText();
            C = Boton3.getText();
            D = Boton4.getText();
            E = Boton5.getText();
            F = Boton6.getText();
            G = Boton7.getText();
            H = Boton8.getText();
            I = Boton9.getText();
            //-----------------------
            if ("X".equals(E)){
if (((A.equals(E))&&(E.equals(I)))||((C.equals(E))&&(E.equals(G)))||((D.equals(E))&&(E.equals(F)))||((B.equals(E))&&(E.equals(H)))){
            JOptionPane.showMessageDialog(null, "Gano el jugador con X","Ganador",JOptionPane.INFORMATION_MESSAGE);
            Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);              
            }  else{}    
}
if ("O".equals(E)){
if (((A.equals(E))&&(E.equals(I)))||((C.equals(E))&&(E.equals(G)))||((D.equals(E))&&(E.equals(F)))||((B.equals(E))&&(E.equals(H)))){
            JOptionPane.showMessageDialog(null, "Gano el jugador con O","Ganador",JOptionPane.INFORMATION_MESSAGE);
            Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
        } else{}
}


    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        if (N==0){
            Boton2.setText("X");
            N = 1;
            } else {
                 Boton2.setText("O");
                 N = 0;
                    }
            Boton2.setEnabled(false);
            //----------------------- 
            A = Boton1.getText();
            B = Boton2.getText();
            C = Boton3.getText();
            D = Boton4.getText();
            E = Boton5.getText();
            F = Boton6.getText();
            G = Boton7.getText();
            H = Boton8.getText();
            I = Boton9.getText();
            //-----------------------
if ("X".equals(B)){
if (((B.equals(A))&&(B.equals(C)))||((B.equals(E))&&(E.equals(H)))){
                JOptionPane.showMessageDialog(null, "Gano el jugador con X","Ganador",JOptionPane.INFORMATION_MESSAGE);
                Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
            } else{}    
            }
if ("O".equals(B)){
    if (((B.equals(A))&&(B.equals(C)))||((B.equals(E))&&(E.equals(H)))){
                JOptionPane.showMessageDialog(null, "Gano el jugador con O","Ganador",JOptionPane.INFORMATION_MESSAGE);
                Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
            } else{}   
} 
            
            
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        if (N==0){
            Boton3.setText("X");
            N = 1;
            } else {
                 Boton3.setText("O");
                 N = 0;
                    }
            Boton3.setEnabled(false);
            //----------------------- 
            A = Boton1.getText();
            B = Boton2.getText();
            C = Boton3.getText();
            D = Boton4.getText();
            E = Boton5.getText();
            F = Boton6.getText();
            G = Boton7.getText();
            H = Boton8.getText();
            I = Boton9.getText();
            //-----------------------
            if ("X".equals(C)){
              if (((C.equals(B))&&(B.equals(A)))||((C.equals(F))&&(F.equals(I)))||((C.equals(E))&&(E.equals(G)))){
                JOptionPane.showMessageDialog(null, "Gano el jugador con X","Ganador",JOptionPane.INFORMATION_MESSAGE);
                Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
             }  else{}
            }
        if ("O".equals(C)){
            if (((C.equals(B))&&(B.equals(A)))||((C.equals(F))&&(F.equals(I)))||((C.equals(E))&&(E.equals(G)))){
                JOptionPane.showMessageDialog(null, "Gano el jugador con O","Ganador",JOptionPane.INFORMATION_MESSAGE);
                Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
             }  else{}
        }    
    }//GEN-LAST:event_Boton3ActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        if (N==0){
            Boton4.setText("X");
            N = 1;
            } else {
                 Boton4.setText("O");
                 N = 0;
                    }
            Boton4.setEnabled(false);
            //----------------------- 
            A = Boton1.getText();
            B = Boton2.getText();
            C = Boton3.getText();
            D = Boton4.getText();
            E = Boton5.getText();
            F = Boton6.getText();
            G = Boton7.getText();
            H = Boton8.getText();
            I = Boton9.getText();
            //-----------------------
            if ("X".equals(D)){
                if (((D.equals(A))&&(D.equals(G)))||((D.equals(E))&&(E.equals(F)))){
                JOptionPane.showMessageDialog(null, "Gano el jugador con X","Ganador",JOptionPane.INFORMATION_MESSAGE);
                Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
                } else {}   
           }
          if ("O".equals(D)){
              if (((D.equals(A))&&(D.equals(G)))||((D.equals(E))&&(E.equals(F)))){
                JOptionPane.showMessageDialog(null, "Gano el jugador con O","Ganador",JOptionPane.INFORMATION_MESSAGE);
                Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
                } else {} 
          }
            
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        if (N==0){
            Boton6.setText("X");
            N = 1;
            } else {
                 Boton6.setText("O");
                 N = 0;
                    }
            Boton6.setEnabled(false);
            //----------------------- 
            A = Boton1.getText();
            B = Boton2.getText();
            C = Boton3.getText();
            D = Boton4.getText();
            E = Boton5.getText();
            F = Boton6.getText();
            G = Boton7.getText();
            H = Boton8.getText();
            I = Boton9.getText();
            //-----------------------
            if ("X".equals(F)){
              if (((F.equals(C))&&(F.equals(I)))||((F.equals(E))&&(E.equals(D)))){
            JOptionPane.showMessageDialog(null, "Gano el jugador con X","Ganador",JOptionPane.INFORMATION_MESSAGE);   
            Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
            }  else{}
              
           }
           if ("O".equals(F)){
            if (((F.equals(C))&&(F.equals(I)))||((F.equals(E))&&(E.equals(D)))){
            JOptionPane.showMessageDialog(null, "Gano el jugador con O","Ganador",JOptionPane.INFORMATION_MESSAGE); 
            Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
            }  else{}
               
           }
            
                  
    }//GEN-LAST:event_Boton6ActionPerformed

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        if (N==0){
            Boton8.setText("X");
            N = 1;
            } else {
                 Boton8.setText("O");
                 N = 0;
                    }
            Boton8.setEnabled(false);
            //----------------------- 
            A = Boton1.getText();
            B = Boton2.getText();
            C = Boton3.getText();
            D = Boton4.getText();
            E = Boton5.getText();
            F = Boton6.getText();
            G = Boton7.getText();
            H = Boton8.getText();
            I = Boton9.getText();
            //-----------------------
         if ("X".equals(H)){
            if (((H.equals(G))&&(H.equals(I)))||((H.equals(E))&&(E.equals(B)))){
            JOptionPane.showMessageDialog(null, "Gano el jugador con X","Ganador",JOptionPane.INFORMATION_MESSAGE);
            Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
            } else{}
           }
         if ("O".equals(H)){
            if (((H.equals(G))&&(H.equals(I)))||((H.equals(E))&&(E.equals(B)))){
            JOptionPane.showMessageDialog(null, "Gano el jugador con O","Ganador",JOptionPane.INFORMATION_MESSAGE);
            Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
            } else{} 
          }
    }//GEN-LAST:event_Boton8ActionPerformed

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        if (N==0){
            Boton7.setText("X");
            N = 1;
            } else {
                 Boton7.setText("O");
                 N = 0;
                    }
            Boton7.setEnabled(false);
            //----------------------- 
            A = Boton1.getText();
            B = Boton2.getText();
            C = Boton3.getText();
            D = Boton4.getText();
            E = Boton5.getText();
            F = Boton6.getText();
            G = Boton7.getText();
            H = Boton8.getText();
            I = Boton9.getText();
            //-----------------------
           if ("X".equals(G)){
             if (((G.equals(D))&&(D.equals(A)))||((G.equals(H))&&(H.equals(I)))||((G.equals(E))&&(E.equals(C)))){
             JOptionPane.showMessageDialog(null, "Gano el jugador con X","Ganador",JOptionPane.INFORMATION_MESSAGE);
             Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
             } else {}
           }
          if ("O".equals(G)){
              if (((G.equals(D))&&(D.equals(A)))||((G.equals(H))&&(H.equals(I)))||((G.equals(E))&&(E.equals(C)))){
             JOptionPane.showMessageDialog(null, "Gano el jugador con O","Ganador",JOptionPane.INFORMATION_MESSAGE);
             Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
             } else {}
          }
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
     if (N==0){
            Boton9.setText("X");
            N = 1;
            } else {
                 Boton9.setText("O");
                 N = 0;
                    }
            Boton9.setEnabled(false);
            //----------------------- 
            A = Boton1.getText();
            B = Boton2.getText();
            C = Boton3.getText();
            D = Boton4.getText();
            E = Boton5.getText();
            F = Boton6.getText();
            G = Boton7.getText();
            H = Boton8.getText();
            I = Boton9.getText();
            //-----------------------
            if ("X".equals(I)){
              if (((I.equals(H))&&(H.equals(G)))||((I.equals(F))&&(F.equals(C)))||((I.equals(E))&&(E.equals(A)))){
            JOptionPane.showMessageDialog(null, "Gano el jugador con X","Ganador",JOptionPane.INFORMATION_MESSAGE);   
            Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
            } else {}  
           }
          if ("O".equals(I)){
            if (((I.equals(H))&&(H.equals(G)))||((I.equals(F))&&(F.equals(C)))||((I.equals(E))&&(E.equals(A)))){
            JOptionPane.showMessageDialog(null, "Gano el jugador con O","Ganador",JOptionPane.INFORMATION_MESSAGE);
            Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
            } else {}    
          }  
            
            
            
    }//GEN-LAST:event_Boton9ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JSeparator Separador;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
